[package]
name = "sine-sound"
version = "0.1.0"
authors = ["sniggel <grmontpetit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eventual = "0.1.7"
cpal = "0.10.0"
